services:
  odoo:
    container_name: odoo_igniter
    image: odoo:18
    restart: always
    depends_on:
      - postgres
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf.template
      - ./addons/:/mnt/extra-addons
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - HOST=postgres
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_ADMIN_PASSWORD=${ODOO_ADMIN_PASSWORD}
    entrypoint: /entrypoint.sh
    networks:
      - odoo18_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo.rule=Host(`${ODOO_HOST}`)"
      - "traefik.http.routers.odoo.entrypoints=websecure"
      - "traefik.http.routers.odoo.tls=true"
      - "traefik.http.routers.odoo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.odoo.service=odoo"
      - "traefik.http.services.odoo.loadbalancer.server.port=8069"

  postgres:
    command: postgres -c log_connections=on -c log_min_messages=DEBUG1
    container_name: postgres_igniter
    image: postgres:17.0-bullseye
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data 
    networks:
      - odoo18_net
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  odoo18_net:
  traefik_net:
    external: true

volumes:
  db_data:
  odoo_data:
