services:
  odoo:
    container_name: odoo_igniter
    image: odoo:18
    restart: always
    depends_on:
      - postgres
    volumes:
      - odoo_data:/var/lib/odoo
      - ./odoo.conf.template:/etc/odoo/odoo.conf.template
      - ./addons/:/mnt/extra-addons
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - HOST=postgres
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_ADMIN_PASSWORD=${ODOO_ADMIN_PASSWORD}
    entrypoint: /entrypoint.sh
    command: odoo
    networks:
      - odoo18_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.odoo18.rule=Host(`${ODOO_HOST}`)"
      - "traefik.http.routers.odoo18.entrypoints=websecure"
      - "traefik.http.routers.odoo18.tls.certresolver=letsencrypt"
      - "traefik.http.services.odoo18.loadbalancer.server.port=8069"

  postgres:
    container_name: postgres_igniter
    image: postgres:17.0-bullseye
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - odoo18_net
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  odoo18_net:
  traefik_net:
    external: true

volumes:
  db_data:
  odoo_data:
